document.addEventListener('DOMContentLoaded',function(){
 const get=(k,f=[])=>{try{return JSON.parse(localStorage.getItem(k))||f}catch(e){return f}},set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
 if(localStorage.getItem('isLoggedIn')!=='true'){window.location.href='index.html';return}
 const name=localStorage.getItem('customerName')||'Guest User',phone=localStorage.getItem('customerPhone')||'Not available';
 document.getElementById('profileName').textContent=name;document.getElementById('profilePhone').textContent='+91 '+phone;document.getElementById('profileAvatar').textContent=name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase();
 const content=document.getElementById('profileContent'),orders=()=>get('grillHouseOrders'),fav=()=>get('grillHouseFavourites'),notes=()=>get('grillHouseNotifications'),cart=()=>get('grillHouseCart');
 document.getElementById('coinCount').textContent=250+(orders().length*50);
 const empty=(icon,title,text,action='')=>`<div class="profile-empty"><i class="${icon}"></i><h3>${title}</h3><p>${text}</p>${action}</div>`;
 function render(section){
  if(section==='orders'){let list=orders();content.innerHTML=`<div class="profile-panel"><h1>Recent Orders</h1><p class="profile-sub">Your Grill House orders will always be here.</p>${list.length?list.map(o=>`<article class="order-card"><div class="order-top"><h4>${o.id}</h4><span class="order-status">${o.status||'Order placed'}</span></div><p>${o.date} · ${o.items.reduce((n,x)=>n+x.qty,0)} item(s)</p><b>₹${o.total}</b><button class="profile-link-btn" data-reorder="${o.id}" style="float:right">Reorder</button></article>`).join(''):empty('fa-solid fa-bag-shopping','No orders yet','Your next Grill House favourite is waiting.','<a href="menu.html"><button class="profile-primary">ORDER NOW</button></a>')}</div>`}
  if(section==='addresses'){let a=get('grillHouseAddresses');content.innerHTML=`<div class="profile-panel"><h1>Saved Addresses</h1><p class="profile-sub">Save delivery details to checkout faster.</p><button class="profile-primary" id="showAddressForm">+ ADD ADDRESS</button><div id="addressFormWrap"></div><div id="addressList">${a.length?a.map((x,i)=>`<article class="address-card"><div class="address-actions"><h4>${x.label}</h4><span><button class="profile-link-btn" data-edit-address="${i}">Edit</button><button class="profile-link-btn" data-delete-address="${i}">Delete</button></span></div><p>${x.text}</p></article>`).join(''):empty('fa-solid fa-location-dot','No saved addresses','Add an address and checkout will feel even easier.')}</div></div>`;document.getElementById('showAddressForm').onclick=()=>showAddress();}
  if(section==='favourites'){let f=fav();content.innerHTML=`<div class="profile-panel"><h1>Favourite Items</h1><p class="profile-sub">The dishes you never want to forget.</p>${f.length?`<div class="favourite-grid">${f.map((x,i)=>`<article class="fav-card"><img src="${x.image||'images/logo 1.png'}" alt=""><div><h4>${x.name}</h4><p>₹${x.price}</p><button class="profile-link-btn" data-fav-cart="${i}">Add to Cart</button><button class="profile-link-btn" data-fav-remove="${i}">Remove</button></div></article>`).join('')}</div>`:empty('fa-solid fa-heart','No favourites yet','Tap the heart on a menu item to save it here.')}</div>`}
  if(section==='deals')content.innerHTML='<div class="profile-panel"><h1>Saved Deals</h1><p class="profile-sub">Exclusive Grill House treats, ready when you are.</p><article class="deal-card"><h4>GRILL20 · 20% OFF</h4><p>Save 20% on orders over ₹499. Apply at checkout.</p></article><article class="deal-card"><h4>WELCOME100 · ₹100 OFF</h4><p>A warm welcome for your first Grill House order.</p></article></div>';
  if(section==='notifications'){let n=notes();content.innerHTML=`<div class="profile-panel"><h1>Notifications</h1><p class="profile-sub">Order updates and Grill House news.</p>${n.length?n.map(x=>`<article class="notice-card"><b>${x.title}</b><p>${x.text}</p><small>${x.date||''}</small></article>`).join(''):empty('fa-solid fa-bell','You are all caught up','We’ll let you know when there is something worth tasting.')}</div>`}
  if(section==='support')content.innerHTML='<div class="profile-panel"><h1>Help & Support</h1><p class="profile-sub">We are here to make every order easy.</p><article class="notice-card"><b>Need help with an order?</b><p>Call us at +91 98765 43210 between 11:00 AM and 10:30 PM.</p></article><article class="notice-card"><b>Have feedback?</b><p>We love hearing how we can make your next visit better.</p></article></div>';
  if(section==='about')content.innerHTML='<div class="profile-panel"><h1>About Grill House</h1><p class="profile-sub">Food made with warmth, flavour, and a touch of fire.</p><article class="notice-card"><b>Our Promise</b><p>Thoughtfully prepared food, welcoming service, and dishes made for sharing.</p></article></div>';
  if(section==='settings')content.innerHTML='<div class="profile-panel"><h1>Settings</h1><p class="profile-sub">Manage your Grill House preferences.</p><div class="settings-row"><span>Order updates</span><span class="profile-toggle"></span></div><div class="settings-row"><span>Offers and rewards</span><span class="profile-toggle"></span></div><div class="settings-row"><span>Account details are saved securely in this browser</span></div></div>';
  bindDynamic();
 }
 function showAddress(i){let a=get('grillHouseAddresses'),x=i==null?{}:a[i];document.getElementById('addressFormWrap').innerHTML=`<form class="address-form" id="addressForm"><input name="label" required placeholder="Label (Home, Work)" value="${x.label||''}"><input name="text" required placeholder="Full delivery address" value="${x.text||''}"><button class="profile-primary">Save Address</button></form>`;document.getElementById('addressForm').onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));i==null?a.push(d):a[i]=d;set('grillHouseAddresses',a);render('addresses')}}
 function bindDynamic(){document.querySelectorAll('[data-delete-address]').forEach(b=>b.onclick=()=>{let a=get('grillHouseAddresses');a.splice(+b.dataset.deleteAddress,1);set('grillHouseAddresses',a);render('addresses')});document.querySelectorAll('[data-edit-address]').forEach(b=>showAddress(+b.dataset.editAddress));document.querySelectorAll('[data-reorder]').forEach(b=>b.onclick=()=>{let o=orders().find(x=>x.id===b.dataset.reorder);set('grillHouseCart',o.items);window.GrillCart?.install();alert('Order added back to your cart.')});document.querySelectorAll('[data-fav-remove]').forEach(b=>b.onclick=()=>{let f=fav();f.splice(+b.dataset.favRemove,1);set('grillHouseFavourites',f);render('favourites')});document.querySelectorAll('[data-fav-cart]').forEach(b=>b.onclick=()=>{let f=fav()[+b.dataset.favCart],c=cart(),hit=c.find(x=>x.id===f.id);hit?hit.qty++:c.push({...f,qty:1});set('grillHouseCart',c);window.GrillCart?.install();alert('Added to cart.')})}
 document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-section]').forEach(x=>x.classList.toggle('active',x===b));render(b.dataset.section)});document.getElementById('logoutBtn').onclick=()=>{if(confirm('Are you sure you want to logout?')){['customerName','customerPhone','isLoggedIn'].forEach(k=>localStorage.removeItem(k));window.location.href='index.html'}};render('orders');
});
